### ISSUE TITLE
StateVector.ravel() cannot be indexed

### ISSUE THREAD

**Issue by sglvladi** [dstl/Stone-Soup#268]
It seems like the latest changes to ``StateVector`` have broken indexing of the array returned when using ``ravel()``.

An example is given bellow:

``` python
from stonesoup.types.array import StateVector
a = StateVector([0, 0])
a
Out[4]: 
StateVector([[0],
             [0]])
b = a.ravel()
b
Out[6]: StateVector([0, 0])
b[0]
Traceback (most recent call last):
  File "C:\Users\sglvladi\AppData\Roaming\Python\Python37\site-packages\IPython\core\interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-54af0eb47770>", line 1, in <module>
    b[0]
  File "C:\Users\sglvladi\Documents\GitHub\StoneSoup-tf\stonesoup\types\array.py", line 107, in __getitem__
    return self._cast(super().__getitem__(item))
IndexError: too many indices for array
```

The array returned by ``ravel()`` is an invalid ``StateVector`` object. I suspect a potential workaround would be to override the method so that a ``numpy.ndarray`` object is returned instead. 

Any thoughts?

**Comment by sdhiscocks** [comment]
I think it makes sense to override the methods, also for `flatten`. I think the below should work:
```python
    def flatten(self, *args, **kwargs):
        return self._cast(super().flatten(*args, **kwargs))

    def ravel(self, *args, **kwargs):
        return self._cast(super().ravel(*args, **kwargs))

```

**Comment by sglvladi** [comment]
@sdhiscocks thanks 👍  I've added a PR with the above changes
