### ISSUE TITLE
OSPAMetric change? TypeError: got an unexpected keyword argument 'measurement_model_track'

### ISSUE THREAD

**Issue by apiszcz** [dstl/Stone-Soup#305]
Previously I setup metrics with

```
       self.basic_calculator = BasicMetrics()
       self.ospa_calculator = OSPAMetric(c=10,
                                          p=1,
                                          measurement_model_track=self.measurement_model,
                                          measurement_model_truth=self.measurement_model)
```

Stack trace

```
2020-09-27T10:04:39.601007> metrics_setup
Traceback (most recent call last):
  File "lib\_test\test.py", line 4618, in <module>
    otestsim.run(oc, ol, ou, modes, src)
  File "lib\_test\test.py", line 1786, in run
    self.metrics_setup()
  File "lib\_test\test.py", line 1707, in metrics_setup
    measurement_model_truth=self.measurement_model)
  File "C:\t\ss\lib\lib\site-packages\stonesoup\base.py", line 195, in __init__
    super(cls, self).__init__(*args, **kwargs)
  File "C:\t\ss\lib\lib\site-packages\stonesoup\metricgenerator\ospametric.py", line 35, in __init__
    super().__init__(*args, **kwargs)
  File "C:\t\ss\lib\lib\site-packages\stonesoup\base.py", line 195, in __init__
    super(cls, self).__init__(*args, **kwargs)
  File "C:\t\ss\lib\lib\site-packages\stonesoup\base.py", line 301, in __init__
    bound_arguments = init_signature.bind(*args, **kwargs)
  File "C:\t\ss\lib\python\lib\inspect.py", line 3015, in bind
    return args[0]._bind(args[1:], kwargs)
  File "C:\t\ss\lib\python\lib\inspect.py", line 3006, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'measurement_model_track'
```

**Comment by apiszcz** [comment]
I used metrics.py as a guide, and made the necessary changes. So far all set.
