### ISSUE TITLE
*** AttributeError: Platform system cannot be set on sensors that were created with a default platform

### ISSUE THREAD

**Issue by apiszcz** [dstl/Stone-Soup#363]
Note:
The example uses https://stonesoup.readthedocs.io/en/v0.1b2_a/auto_examples/Moving_Platform_Simulation.html.
I would like to create use a the AESARadar instead of the RadarElevationBearingRangeRate. 

After reviewing and using a very similar setup to the test code for sensors I am getting the following stack trace using the AESARadar.

1. What am I missing concerning the platform assignment (add_sensor), the default platform apparently was ok for the RadarElevationBearingRangeRate case.
2. Do I need to specify a beam sweep sequence or is that handled by the model?

Stacktrace:
```
self.sensor_platform.add_sensor(self.radar,mounting_offset=self.radar_mounting_offsets,rotation_offset=self.radar_rotation_offsets)
*** AttributeError: Platform system cannot be set on sensors that were created with a default platform
Traceback (most recent call last):
  File "TEST\lib\lib\site-packages\stonesoup\platform\base.py", line 211, in add_sensor
    sensor.platform_system = weakref.ref(self)
  File "TEST\lib\lib\site-packages\stonesoup\sensor\base.py", line 44, in platform_system
    self._set_platform_system(value)
  File "TEST\lib\lib\site-packages\stonesoup\sensor\sensor.py", line 47, in _set_platform_system
    raise AttributeError('Platform system cannot be set on sensors that were created with '


--

```
    def init_sensor_platform(self):
        # Define the initial platform position, in this case the origin x, xv, y, yv, z, zv
        self.initial_loc = StateVector([[0], [0], [0], [50], [8000], [0]])
        self.initial_state = State(self.initial_loc, self.start_time)

        # Define transition model and position for 3D platform, x, y, z
        self.transition_model = CombinedLinearGaussianTransitionModel(
                [ConstantVelocity(0.), ConstantVelocity(0.), ConstantVelocity(0.)])

        # create our fixed platform, position x, y, z, velocity xv, yv, zv
        self.sensor_platform = MovingPlatform(  states              = self.initial_state,
                                                position_mapping    = (0, 2, 4),
                                                velocity_mapping    = (1, 3, 5),
                                                transition_model    = self.transition_model)

```

    def init_aesa(self):
        start_time = datetime.datetime.utcnow()
        r = {
             'antenna_gain'             : 30,
             'azimuth'                  : np.deg2rad(60),
             'bandwidth'                : 30e6,
             'beam_width'               : np.deg2rad(10),
             'centre'                   : [np.pi/45, np.pi/45],
             'degree_per_s'             : np.pi/10,
             'duty_cycle'               : 0.1,
             'elevation'                : np.deg2rad(60),
             'frame'                    : [np.pi/9, np.pi/18],
             'frequency'                : 100e6,
             'number_pulses'            : 5,
             'position_mapping'         : [0, 2, 4],
             'position'                 : StateVector([0.0] * 3),
             'probability_false_alarm'  : 1e-6,
             'orientation'              : StateVector([0.0] * 3),
             'rcs'                      : 1.0,
             'receiver_noise'           : 3,
             'separation'               : np.pi/36,
             'swerling_on'              : False,
             'beam_power'               : 100000.0
             }

        r.update({'beam_shape'   : Beam2DGaussian(r['beam_power'])})
        r.update({'beam_pattern' : BeamSweep( angle_per_s = r['degree_per_s'],
                                            centre        = r['centre'],
                                            frame         = r['frame'],
                                            separation    = r['separation'],
                                            init_time     = start_time
                                           ) }  )

        r.update({'measurement_model' : LinearGaussian(6, [0, 2, 4], np.diag([0.5, 0.5, 0.5])) } )

        from stonesoup.sensor.radar.radar import AESARadar
        self.radar = AESARadar(
                                antenna_gain            = r['antenna_gain'],
                                band_width              = r['bandwidth'],
                                beam_shape              = r['beam_shape'],
                                beam_transition_model   = r['beam_pattern'],
                                beam_width              = r['beam_width'],
                                duty_cycle              = r['duty_cycle'],
                                frequency               = r['frequency'],
                                measurement_model       = r['measurement_model'],
                                number_pulses           = r['number_pulses'],
                                orientation             = r['orientation'],
                                position_mapping        = r['position_mapping'],
                                position                = r['position'],
                                probability_false_alarm = r['probability_false_alarm'],
                                rcs                     = r['rcs'],
                                receiver_noise          = r['receiver_noise'],
                                swerling_on             = r['swerling_on']
                              )

        # radar mountings
        self.radar_mounting_offsets = StateVector([10, 0, 0])  # e.g. nose cone
        self.radar_rotation_offsets = StateVector([0, 0, 0])

        # Mount the radar onto the platform
        self.sensor_platform.add_sensor(self.radar,
                                   mounting_offset=self.radar_mounting_offsets,
                                   rotation_offset=self.radar_rotation_offsets)
```

**Comment by sdhiscocks** [comment]
1. This is caused by providing a `position` and/or `orientation` to the Sensor. Removing those from your initialisation should fix it. https://github.com/dstl/Stone-Soup/blob/61b203f561688ef91dea0f9bd92291e7740994b5/stonesoup/sensor/sensor.py#L15-L19
2. The model should handle it.

**Comment by apiszcz** [comment]
Thank you, initialization successful.

```
                                # orientation             = r['orientation'],
                                # position_mapping        = r['position_mapping'],
                                # position                = r['position'],
```

**Comment by apiszcz** [comment]
I added a print and write to file of the x,y,z position of the sensor in sensor\base.py.
I am expecting to see x,y coordinate sweeps, however I'm only seeing the y value increment.
Looks like there is more to learn on where the AESARadar scan locations (beam) indication is avaialble.

```
    @property
    def position(self) -> Optional[StateVector]:
        """The sensor position on a 3D Cartesian plane, expressed as a 3x1 :class:`StateVector`
        of Cartesian coordinates in the order :math:`x,y,z`.

        .. note::
            This property delegates the actual calculation of position to the platform on which the
            sensor is mounted.

            It is settable if, and only if, the sensor holds its own internal platform."""
        if self.platform is None:
            return None
        ss = self.platform.get_sensor_position(self)
        pos = '%f,%f,%f\n'%(ss[0],ss[1],ss[2])
        if os.path.exists('sensorposition.csv'):
            ostream = open('sensorposition.csv', 'a')
            ostream.write(pos)
        else:
            ostream = open('sensorposition.csv', 'w')
            ostream.write('x,y,z\n')
            ostream.write(pos)
        sys.stdout.write(pos)
        ostream.close()
        return self.platform.get_sensor_position(self)
```

```
0.000000,10.000000,8000.000000
0.000000,10.000000,8000.000000
0.000000,60.000000,8000.000000
0.000000,60.000000,8000.000000
0.000000,110.000000,8000.000000
0.000000,110.000000,8000.000000
0.000000,160.000000,8000.000000
0.000000,160.000000,8000.000000
0.000000,210.000000,8000.000000
0.000000,210.000000,8000.000000
0.000000,260.000000,8000.000000
0.000000,260.000000,8000.000000
0.000000,310.000000,8000.000000
0.000000,310.000000,8000.000000
0.000000,360.000000,8000.000000
0.000000,360.000000,8000.000000
0.000000,410.000000,8000.000000
0.000000,410.000000,8000.000000
0.000000,460.000000,8000.000000
0.000000,460.000000,8000.000000
0.000000,510.000000,8000.000000
0.000000,510.000000,8000.000000
0.000000,560.000000,8000.000000
0.000000,560.000000,8000.000000
0.000000,610.000000,8000.000000
0.000000,610.000000,8000.000000
0.000000,660.000000,8000.000000
0.000000,660.000000,8000.000000
0.000000,710.000000,8000.000000
0.000000,710.000000,8000.000000
0.000000,760.000000,8000.000000
0.000000,760.000000,8000.000000
0.000000,810.000000,8000.000000
0.000000,810.000000,8000.000000
0.000000,860.000000,8000.000000
0.000000,860.000000,8000.000000
0.000000,910.000000,8000.000000
0.000000,910.000000,8000.000000
0.000000,960.000000,8000.000000
0.000000,960.000000,8000.000000
0.000000,1010.000000,8000.000000
0.000000,1010.000000,8000.000000
0.000000,1060.000000,8000.000000
0.000000,1060.000000,8000.000000
0.000000,1110.000000,8000.000000
0.000000,1110.000000,8000.000000
0.000000,1160.000000,8000.000000
0.000000,1160.000000,8000.000000
```

**Comment by sdhiscocks** [comment]
> I added a print and write to file of the x,y,z position of the sensor in sensor\base.py.
> I am expecting to see x,y coordinate sweeps, however I'm only seeing the y value increment.
> Looks like there is more to learn on where the AESARadar scan locations (beam) indication is avaialble.

To get that information, you could use the `BeamSweep.move_beam()` method, passing in the timestamp that you want to know the beams azimuth/elevation, along with the platform position/orientation.

**Comment by apiszcz** [comment]
Additional questions.
1. Do i need to move the beam myself or is that handled in the model/iteration somewhere?
2. In the platform object below, is the position mapping under sensors correct? (0,1,2)

```
MovingPlatform(states=[State(state_vector=StateVector([[   0],
             [   0],
             [   0],
             [  50],
             [8000],
             [   0]]), timestamp=datetime.datetime(2021, 2, 1, 18, 34, 19, 506161)), State(state_vector=StateVector([[   0.],
             [   0.],
             [   0.],
             [  50.],
             [8000.],
             [   0.]]), timestamp=datetime.datetime(2021, 2, 1, 18, 34, 19, 506161))], position_mapping=(0, 2, 4), transition_model=CombinedLinearGaussianTransitionModel(model_list=[ConstantVelocity(noise_diff_coeff=0.0), ConstantVelocity(noise_diff_coeff=0.0), ConstantVelocity(noise_diff_coeff=0.0)]), rotation_offsets=(StateVector([[0],
             [0],
             [0]]),), mounting_offsets=(StateVector([[10],
             [ 0],
             [ 0]]),), sensors=(AESARadar(beam_shape=Beam2DGaussian(peak_power=100000.0, beam_width=None), beam_transition_model=BeamSweep(angle_per_s=0.3141592653589793, frame=[0.3490658503988659, 0.17453292519943295], separation=0.08726646259971647, centre=[0.06981317007977318, 0.06981317007977318], init_time=datetime.datetime(2021, 2, 1, 18, 34, 19, 506161)), duty_cycle=0.1, band_width=30000000.0, receiver_noise=3, frequency=100000000.0, antenna_gain=30, beam_width=0.17453292519943295, rotation_offset=StateVector([[0],
             [0],
             [0]]), position_mapping=(0, 1, 2), measurement_model=LinearGaussian(ndim_state=6, mapping=[0, 2, 4], noise_covar=array([[0.5, 0. , 0. ],
       [0. , 0.5, 0. ],
       [0. , 0. , 0.5]])), number_pulses=5, loss=0, swerling_on=False, rcs=1.0, probability_false_alarm=1e-06),), velocity_mapping=(1, 3, 5))
```

**Comment by apiszcz** [comment]
With the current parameters shown above these are the beam_sweep positions, with what looks like 2.3 scans


![image](https://user-images.githubusercontent.com/1430861/106505233-0663ae00-6496-11eb-94f7-3f293879fc6c.png)


![image](https://user-images.githubusercontent.com/1430861/106505249-0ebbe900-6496-11eb-8ac6-a309f48009e5.png)

**Comment by apiszcz** [comment]
A bit more thought here, I'll need to adjust the scan speed to be less than the step time of the platform. Will review this next.
